# [START gae_python38_cloudsql_config]
runtime: python38

env_variables:
  CLOUD_SQL_USERNAME: admin
  CLOUD_SQL_PASSWORD: hackathon2020
  CLOUD_SQL_DATABASE_NAME: transactions
  CLOUD_SQL_CONNECTION_NAME: central-shade-285805:us-central1:banking-and-finance
# [END gae_python38_cloudsql_config]

vpc_access_connector:
  name: "projects/central-shade-285805/locations/asia-south1/connectors/connect-to-sql"
